import { KoHo, Jaro } from "next/font/google";
import { config } from "@fortawesome/fontawesome-svg-core";
import "@fortawesome/fontawesome-svg-core/styles.css";
import "./globals.css";
import MainMenu from "./components/MainMenu";
import SearchBar from "./components/SearchBar";
config.autoAddCss = false;

const koho = KoHo({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-koho",
  display: "swap",
});

const jaro = Jaro({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-jaro",
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${jaro.variable} ${koho.variable} antialiased`}>
      <body className="flex">
        <MainMenu />
        <div className="flex-1 relative">
          <SearchBar />
          <main className="main-side-margins">{children}</main>
        </div>
      </body>
    </html>
  );
}
