// GLOBAL LAYOUT - This file applies the main menu and search bar accross pages.

import { KoHo, Jaro, Roboto } from 'next/font/google';
import { config } from '@fortawesome/fontawesome-svg-core';
import '@fortawesome/fontawesome-svg-core/styles.css';
import './../styles/globals.css';
import MainMenu from '../../components/shared/MainMenu';
import SearchBar from '../../components/shared/SearchBar';
import { UserProvider } from '@/context/UserContext';
config.autoAddCss = false;

const koho = KoHo({
  subsets: ['latin'],
  weight: ['300', '400', '500', '600', '700'],
  variable: '--font-koho',
  display: 'swap',
});

const jaro = Jaro({
  subsets: ['latin'],
  weight: '400',
  variable: '--font-jaro',
  display: 'swap',
});

const roboto = Roboto({
  subsets: ['latin'],
  weight: '400',
  variable: '--font-roboto',
  display: 'swap',
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${jaro.variable} ${koho.variable} ${roboto.variable} antialiased`}
      suppressHydrationWarning={true}
    >
      <body className="flex" suppressHydrationWarning={true}>
        <UserProvider>
          <>
            <MainMenu />
            <div className="flex-1 relative">
              {/* overflow-y-auto */}
              <SearchBar />
              <main className="main-side-padding">{children}</main>
            </div>
          </>
        </UserProvider>
      </body>
    </html>
  );
}
